### ISSUE TITLE
Images should be resized to fit into content area

### ISSUE THREAD

**Issue by dlemmermann** [gluonhq/rich-text-area#117]
Images are shown at their original size. Their width should be scaled to fit into the content area. Exactly like this text area (of this comment) is doing it.

<img width="952" alt="Screenshot 2022-03-15 at 10 36 19" src="https://user-images.githubusercontent.com/9534301/158349304-9c0d5af0-848f-47c0-8b4f-d3e41d04f8b0.png">

**Comment by jperedadnr** [comment]
Yes, there is a [TODO](https://github.com/gluonhq/rich-text-area/blob/master/src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java#L366) for allowing resizing the image, and another [one](https://github.com/gluonhq/rich-text-area/blob/master/src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java#L371) to clip the image if it is wider than the contentArea.

Since `ImageDecoration` has also width/height parameters, and while the above gets done, another option is to include a small dialog from the Image button, to ask the user to set a size (full size, scaled, 64x64, ...)

**Comment by dlemmermann** [comment]
Sounds good that all of this could be supported. For the time being I would say that the automatic "fit to width" would be the preferred default and sufficient for an M1. Those other options could be supported by applications, as this would require some UI work (e.g. a dialog that prompts for this information). @sten-navie your thoughts?
