### ISSUE TITLE
Use the new text decoration API on the model to improve the demo

### ISSUE THREAD

**Issue by eugener** [gluonhq/rich-text-area#5]
Use the API from issue #4. 
Expose it all the way to the `RichTextArea` component level. 
Use it in the demo by providing toolbar, similar to HTML editor

**Comment by abhinayagarwal** [comment]
In order to do this, we need a `decorate()` method on the Control which when called will apply the decoration on the _selected text_. So, something like this:

```
 public void decorate(TextDecoration decoration);
 ```
 
 This works, however, do we want to expose `TextDecoration`? The control is the highest level API and we could pass an instance of `javafx.scene.text.Font` instead.
 
 ```
 public void decorate(Font font);
 ```
 
 Internally, we should be able to transform an instance of Font to TextDecoration.

**Comment by jperedadnr** [comment]
We don't expose the model to the control so far, but I don't see how  adding 
```
public void decorate(Font font);
```
will work from control to skin?
Typically we only use properties, and the skin listen to changes in these.
Probably it makes sense to have a public `Decoration` class with Font, Colors, and related decorations (similar to  `Selection`), and a property with it. Then the skin should manage internal conversions to get down to `TextDecoration`?

**Comment by abhinayagarwal** [comment]
With #39 already merged, the scope of this issue is mainly limited to https://github.com/gluonhq/rich-text-area/pull/38#issuecomment-1042993030

**Comment by eugener** [comment]
If you play with the demo, you will find a lot of inconsistencies in how the attributes are applied

**Comment by abhinayagarwal** [comment]
The inconsistencies mostly exist because whenever we apply a new TextDecoration which a set attribute, it overrides the previously set other attributes with their default value.
