### ISSUE TITLE
Redo stack cleared after first redo

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/rich-text-area#52]
To reproduce: run app, insert five letters. At this point, undo/redo stacks are empty.

Start undoing (five times). For every undo command, the redo stack increases up until five items (as expected).

Now, redo once. This works fine and the first letter that was inserted is added back again.

But now calling `redo` again won't have any effect: the first time `redo` is called, `InsertTextCmd::doRedo`  calls `insert` which calls `command::execute` that has:

```
undoStack.push(cmd);
redoStack.clear();
```

which clears the redo stack.

This should not happen when the command comes from  `redo`.

**Comment by abhinayagarwal** [comment]
I cannot reproduce this issue. There is currently a [regression in the skin](https://github.com/gluonhq/rich-text-area/blob/master/src/main/java/com/gluonhq/richtext/RichTextAreaSkin.java#L56) where `KeyCodeCombination(Z, SHORTCUT_DOWN, SHIFT_DOWN)` is actually calling `paste()` instead of `redo()`.

**Comment by jperedadnr** [comment]
You are right, I can't reproduce it anymore.
