### ISSUE TITLE
Add disable property to Actions

### ISSUE THREAD

**Issue by jperedadnr** [gluonhq/rich-text-area#59]
Follow up of https://github.com/gluonhq/rich-text-area/pull/53/files#r812390728

**Comment by jperedadnr** [comment]
@eugener The actions are tight to the ViewModel (though so far we keep them stateless, and only pass the viewModel when `apply` is called.
However, adding a `disabledProperty` needs state, and actions should know about the ViewModel. This means that the current static action factory that creates an action (without skin, viewModel) won't work.

Do you see any other way to build the factory only once the skin/viewModel is set, or do you think we could "activate" the `disabledProperty` once the action knows about the viewModel (i.e. the viewModel is created and all actions are notified)?

**Comment by eugener** [comment]
In my view, we'd always have some kind of viewModel there, even with default/empty text buffer. So it should be safe to have only one action factory tied to that one viewModel. I think you already untied the buffer from it - I had no time to look into PR, but saw the notification. 
So the "disabled" state should always reflect current state of viewModel even with empty buffer. Once we assign new buffer to the viewModel, that state will change and actions disable state might too.  We do now have to create actions by passing viewModel into them instead of using it in `apply`, but that should not be a problem as viewModel itself does not change. 
Let me if you see any flaws in  my thinking

**Comment by eugener** [comment]
I don't think we need static factory if we have it one to one with viewModel. 
It is also one to one with Skin and Control. 
What are the issues you see?

**Comment by jperedadnr** [comment]
If you make the factory non-static, you can't expose it from the skin to the control, and the factory won't be available until the control is added to the scene graph. So far, this means that the toolbar can't add the buttons until that happens.

**Comment by eugener** [comment]
How about have it stay static but bind viewModel into it when it becomes available. Without that model actions don't function and are disabled

**Comment by jperedadnr** [comment]
I can pass the VM to the AbstractFactory and have a set with the actions with no-arg constructor (undo/redo, cut/copy/paste), and pass to those actions the VM, and set a binding for those actions.
However, this is not easy for the actions that have arguments. I can pass the VM as one of those constructor arguments, but it the action is created before VM is initialized, it will be always null (i.e. Bold button from toolbar).
